# Generated by Django 4.2.1 on 2023-08-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0011_remove_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Sales_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество проданнах товаров')),
                ('earnings', models.IntegerField(default=0, verbose_name='Прибыль')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.products', verbose_name='Название продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Categorys_Sales_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество проданнах товаров')),
                ('earnings', models.IntegerField(default=0, verbose_name='Прибыль')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Название продукта')),
            ],
        ),
    ]
