# Generated by Django 4.2.1 on 2023-08-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_admin_features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys_sales_analysis',
            options={'verbose_name': 'Анализ категории ', 'verbose_name_plural': 'Анализ категорий'},
        ),
        migrations.AlterModelOptions(
            name='products_sales_analysis',
            options={'verbose_name': 'Анализ продажи продукта ', 'verbose_name_plural': 'Анализ продаж продуктов'},
        ),
    ]
