# Generated by Django 4.2.1 on 2023-08-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_admin_features', '0002_alter_categorys_sales_analysis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_Analisys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_paid_orders', models.IntegerField(default=0, verbose_name='Число обычных заказов')),
                ('count_paid_orders_with_delivery', models.IntegerField(default=0, verbose_name='Заказы с доставкой')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Анализ заказов',
                'verbose_name_plural': 'Анализ заказов',
            },
        ),
        migrations.CreateModel(
            name='Sales_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.IntegerField(default=0, verbose_name='Прибыль')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Прибыль',
                'verbose_name_plural': 'Прибыль',
            },
        ),
        migrations.CreateModel(
            name='Users_Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Уникальные посетители')),
                ('new_user', models.IntegerField(default=0, verbose_name='Новые пользователи')),
                ('delete_user', models.IntegerField(default=0, verbose_name='Удаленные пользователи')),
                ('subscriber', models.IntegerField(default=0, verbose_name='Пользователи с рассылкой')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Анализ пользователелей',
                'verbose_name_plural': 'Анализ пользователелей',
            },
        ),
        migrations.AddField(
            model_name='products_sales_analysis',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
    ]
