# Generated by Django 4.2.1 on 2023-08-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_admin_features', '0003_orders_analisys_sales_analysis_users_analisis_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders_Analisys',
            new_name='Orders_Analysys',
        ),
        migrations.RenameModel(
            old_name='Users_Analisis',
            new_name='Users_Analysis',
        ),
    ]
