# Generated by Django 4.2.1 on 2023-09-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_admin_features', '0004_rename_orders_analisys_orders_analysys_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders_Analysys',
            new_name='Orders_Analysis',
        ),
    ]
