# Generated by Django 4.2.1 on 2023-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_photos_category_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='first_img',
            field=models.BooleanField(default=False, verbose_name='Главная картинка'),
        ),
    ]
