# Generated by Django 4.2.1 on 2023-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_images_first_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mailing_list',
            field=models.BooleanField(blank=True, default=False, verbose_name='Рассылка'),
        ),
    ]
