# Generated by Django 4.2.1 on 2023-07-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_users_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='first_price',
            field=models.IntegerField(verbose_name='Первоначальная цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_price',
            field=models.IntegerField(blank=True, verbose_name='Конечная  цена'),
        ),
    ]
