# Generated by Django 4.2.1 on 2023-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_products_first_price_alter_products_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка от 1 до 10 '),
        ),
    ]
