# Generated by Django 4.2.1 on 2023-08-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='slug',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции'),
        ),
    ]
