# Generated by Django 4.2.1 on 2023-09-07 14:22

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_transactions_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=30, verbose_name='Название характеристки')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристи товаров',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Неоправленное письмо',
                'verbose_name_plural': 'Неоправленные письма',
            },
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='photo',
            field=models.ImageField(default='shop/static/img/favicon.svg', upload_to='img_category/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='shop/static/img/favicon.svg', upload_to='user_avatar/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_characteristic',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='shop.characteristic', verbose_name='Характеристики'),
        ),
    ]
