# Generated by Django 4.2.1 on 2023-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_characteristic_emails_manufacturer_photo_users_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
    ]
