# Generated by Django 4.2.1 on 2023-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_images_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
