# Generated by Django 4.2.1 on 2023-10-14 13:12

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_users_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_characteristic',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='characteristics', to='shop.characteristic', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_photos',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='images', to='shop.product_images', verbose_name='Изображения'),
        ),
    ]
