# Generated by Django 4.2.1 on 2023-10-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_products_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufaturer', to='shop.manufacturer', verbose_name='Производитель'),
        ),
    ]
