# Generated by Django 4.2.1 on 2023-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_products_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(upload_to='img_category/%Y/%m/%d/', verbose_name='Изображение категории'),
        ),
    ]
