# Generated by Django 4.2.1 on 2023-11-12 19:11

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_category_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Конечная  цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='shop.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_characteristic',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='characteristics', to='shop.characteristic', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_photos',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='images', to='shop.product_images', verbose_name='Изображения'),
        ),
    ]
