# Generated by Django 4.2.1 on 2023-11-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_liked_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_product',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
