# Generated by Django 4.2.1 on 2023-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_liked_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
