# Generated by Django 4.2.1 on 2023-06-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=30, unique=True, verbose_name='Номер машины')),
                ('car_brand', models.CharField(max_length=60, verbose_name='Номер машины')),
                ('payload', models.IntegerField(default=1500, verbose_name='Грузоподъемность')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.cars', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Заказ на день',
                'verbose_name_plural': 'Заказы на день',
            },
        ),
    ]
