# Generated by Django 4.2.1 on 2023-06-12 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('working_with_orders', '0002_cancelled_orders_installments_orders_with_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=30, unique=True, verbose_name='Номер машины')),
                ('car_brand', models.CharField(max_length=60, verbose_name='Номер машины')),
                ('payload', models.IntegerField(default=1500, verbose_name='Грузоподъемность')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.cars', verbose_name='Машина')),
                ('orders', sortedm2m.fields.SortedManyToManyField(help_text=None, to='working_with_orders.orders_with_delivery', verbose_name='Заказы')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ на день',
                'verbose_name_plural': 'Заказы на день',
            },
        ),
    ]
