# Generated by Django 4.2.1 on 2023-06-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_of_1_product', models.FloatField(verbose_name='Цена 1 продукта')),
                ('numbers_of_product', models.IntegerField(verbose_name='Количество продуктов')),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
                ('total_price', models.FloatField(blank=True, verbose_name='Общая стоимость')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата закупки')),
            ],
            options={
                'verbose_name': 'Заказ компании',
                'verbose_name_plural': 'Заказы компании',
            },
        ),
    ]
