# Generated by Django 4.2.1 on 2023-06-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('company_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_orders',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='company_orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.products', verbose_name='Продукт'),
        ),
    ]
