# Generated by Django 4.2.1 on 2023-06-12 08:36

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('working_with_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelled_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='working_with_orders.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отмененный заказ',
                'verbose_name_plural': 'Отменные заказы',
            },
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_per_month', models.FloatField(verbose_name='Месячная плата')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='working_with_orders.orders', verbose_name='Заказ')),
                ('transactions', sortedm2m.fields.SortedManyToManyField(help_text=None, to='shop.transactions', verbose_name='Транзакции')),
            ],
            options={
                'verbose_name': 'Заказ с рассрочкой',
                'verbose_name_plural': 'Заказы с рассрочкой',
            },
        ),
        migrations.CreateModel(
            name='Orders_With_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.BooleanField(default=False, verbose_name='Состояние')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='working_with_orders.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ с доставкой',
                'verbose_name_plural': 'Заказы с доставкой',
            },
        ),
        migrations.CreateModel(
            name='Paid_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='working_with_orders.orders', verbose_name='Заказ')),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.transactions', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Оплаченный заказ',
                'verbose_name_plural': 'Оплаченные заказы',
            },
        ),
        migrations.DeleteModel(
            name='Paid_Order',
        ),
    ]
