# Generated by Django 4.2.1 on 2023-08-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_with_orders', '0003_rename_dicription_payment_method_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installments',
            name='order',
        ),
        migrations.RemoveField(
            model_name='installments',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Cancelled_Orders',
        ),
        migrations.DeleteModel(
            name='Installments',
        ),
    ]
