# Generated by Django 4.2.1 on 2023-10-16 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0020_alter_products_manufacturer'),
        ('working_with_orders', '0005_orders_paid_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_points',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='shop.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='order_points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
