# Generated by Django 4.2.1 on 2023-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_with_orders', '0006_alter_order_points_product_alter_order_points_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paid_order',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Не оплачено', 'Не оплачено'), ('Оплачено', 'Оплачено'), ('Доставка', 'Доставка')], default='Не оплачено', max_length=50, verbose_name='Статус'),
        ),
    ]
